/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 scene.gltf 
Author: Grigorii Ischenko (https://sketchfab.com/grigoriyarx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robo-shiba-b4215f3c452c4e7cbe845b56251d2877
Title: Robo Shiba
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { Decal } from '@react-three/drei'

export function Shiba(props) {
  const { nodes, materials } = useGLTF('/assets/robo-shiba/scene.gltf')
  const texture = useTexture("/three.png")
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Shiba_Shiba_0.geometry}
        material={materials.Shiba}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <Decal
          //debug // Makes "bounding box" of the decal visible
          position={[0, 10, 32]} // Position of the decal
          rotation={[0, 0, 0]} // Rotation of the decal (can be a vector or a degree in radians)
          scale={10} // Scale of the decal
        >
          <meshBasicMaterial 
            map={texture} 
            polygonOffset
            polygonOffsetFactor={-1} // The material should take precedence over the original
          />
        </Decal>
      </mesh>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
